# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a3d494c801c4d96e5f24dbaa187f4fcb869d1409c9b62d64bc2c336f0a3f38ab7deb6b4157155748813bab3fc497b6a4fdc8f12a093d4a2dcf03677feef90c

test:
  secret_key_base: 360bf2a4692cddf1fcb0ba9d93df7be1882352bd7dd04f5e2e78f16cfe411a48054482e73b924068293610cd9e9e58681a70ddc0effd8d291d0dd060629b2cf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
